version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "ig-desktop"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'
  # VERSION: Set via environment variable for releases (e.g., VERSION=v1.0.0)
  # Falls back to dev-<commit> or just "dev" if git isn't available
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo ""
  VERSION: '{{.VERSION | default (printf "dev-%s" .GIT_COMMIT) | default "dev"}}'
  VERSION_LDFLAGS: '-X ig-frontend/internal/version.Version={{.VERSION}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

  igd:
    summary: Builds the standalone web server (no Wails dependencies)
    cmds:
      - task: frontend:build
      - mkdir -p {{.BIN_DIR}}
      - go build -ldflags "{{.VERSION_LDFLAGS}}" -tags production,withoutebpf -o {{.BIN_DIR}}/igd ./cmd/igd

  igd:dev:
    summary: Runs the web server in development mode
    deps:
      - frontend:build
    cmds:
      - go run ./cmd/igd --listen :8080 --assets frontend/build

  frontend:build:
    summary: Builds the frontend
    dir: frontend
    cmds:
      - npm run build

