// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct wraps the shared services for the Wails desktop application.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {
	Call as $Call,
	CancellablePromise as $CancellablePromise,
	Create as $Create
} from '@wailsio/runtime';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from '../github.com/wailsapp/wails/v3/pkg/application/models.js';

/**
 * Run initializes the event handlers with the Wails application
 * @param {application$0.App | null} wailsApp
 * @returns {$CancellablePromise<void>}
 */
export function Run(wailsApp) {
	return $Call.ByID(2466114226, wailsApp);
}
