// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEnvironment(arg1) {
  return window['go']['main']['App']['AddEnvironment'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function GetEnvironment(arg1) {
  return window['go']['main']['App']['GetEnvironment'](arg1);
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetK8SConfigForEnvironment(arg1) {
  return window['go']['main']['App']['GetK8SConfigForEnvironment'](arg1);
}

export function GetRuntime(arg1) {
  return window['go']['main']['App']['GetRuntime'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Run() {
  return window['go']['main']['App']['Run']();
}
